### ISSUE TITLE
application.properties 

### ISSUE THREAD

**Issue by trinadhkoya** [AlgiersJUG/spring-boot-postgres-sample#3]
Hello dear,

`spring.datasource.driver-class-name=org.postgresql.Driver `
hopefully it should be like this
But you have mentioned like
`spring.databasedriverClassName=org.postgresql.Driver`
,can you please check out

**Comment by koswald** [comment]
`spring.database.driverClassName=org.postgresql.Driver` worked for me on my [similar project](https://github.com/koswald/Moo-V/blob/master/src/main/resources/application.properties).

I did not fork [the AlgiersJUG project](https://github.com/AlgiersJUG/spring-boot-postgres-sample) but I learned from it.

**Comment by abderraza8k** [comment]
Hi @trinadhkoya and @koswald , the project is pretty old , here's another project based on a newer spring-boot version hope it'll help. [here's the project link](https://github.com/jpuzzler/kata-meetings-api)

**Comment by trinadhkoya** [comment]
cool !! Lemme have a look on it @jpuzzler

**Comment by abderraza8k** [comment]
I just refactored code and upgraded to latest spring boot version (actually 1.4.3.RELEASE), thanks for the issue.
